### ISSUE TITLE
on Startup error 

### ISSUE THREAD

**Issue by Franzferdinan51** [Franzferdinan51/DuckCoin#1]
/home/robin/DuckCoin/main.js:48
class BlockChain {
      ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
robin@Dell-R710:~/DuckCoin$

**Comment by Franzferdinan51** [comment]
presumed that the problem is @ https://github.com/Franzferdinan51/DuckCoin/blob/master/main.js#L48
